### ISSUE TITLE
[Question] Notebook/script showing how to train the model?

### ISSUE THREAD

**Issue by WikKam** [KomeijiForce/EmojiLM#1]
Hi! Your paper is fascinating, would it be possible to share the training notebook/code also? I would like to create a similar model (instead of text-to-emoji I would like to insert related emojis into the text). I would also like to target other language (polish) Thanks in advance!

**Comment by KomeijiForce** [comment]
Hi, WikKam! You can refer to
[https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization](https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization)
to train a seq2seq model following the given scripts.
For Polish Language, you could use a multilingual BART like in
[facebook/mbart-large-50-many-to-many-mmt](https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt)
